### PR TITLE
Request for assessments pagination

### PR DESCRIPTION
**Pull request by j0gurt**
Added functionality for request assessments data **only for Audit page** with query parameters, see bellow:

- **Requested number of page**  - __page
- **Page size** - __page_size
- **For filtering assessment data** - __search 
- **For sorting assessmnet data** - __sort
- **For sort direction** - __sort_desc

### CODE REVIEW

**Comment by AlexNo** [comment]
In general, all very good. Well that all code covered tests, but there is no matching with the requirements adopted in the project.
You need to follow the accepted rules in this project like code convension descrided in [this document](https://github.com/AlexNo/ggrc-core/blob/develop/doc/javascript_conventions.md). Need to fix variable naming in according to the [following](https://github.com/AlexNo/ggrc-core/blob/develop/doc/javascript_conventions.md#variable-naming) and somewhere you exceed the length of the string in 80 characters.

**Comment by j0gurt** [comment]
Thanks I'll fix it

**Comment by j0gurt** [comment]
Updated

**Comment by AlexNo** [comment]
Thanks for the update. Approved.

**Pull request merged**
